# Generated by Django 3.2 on 2021-06-07 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('product_image', models.ImageField(upload_to='media/')),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
